# Issues about docstring comments will be covered once we have enough coverage
# TODO: enable when we have coverage for docstring comments
# issues:
#   # The list of ids of default excludes to include or disable.
#   include:
#     - EXC0002 # enable comments checks from golint

linters-settings:
  funlen:
    # Set the maximum number of lines in a function (default: 60)
    # TODO: reduce over time to improve function readability
    lines: 110
    # Set the maximum number of statements in a function (default: 40)
    statements: 60
    
# Default linters configuration: Add more over time as needed
linters:
  disable-all: true # Disable all linters to add them incrementally
  enable:
    - asciicheck
#     - bodyclose
#     - depguard
#     - dogsled
#     - dupl
#     - errcheck
#     - exportloopref
#     - funlen
#     - gocognit
#     - goconst
#     - gocritic
#     - gocyclo
#     - gofmt
#     - goimports
#     - goprintffuncname
#     - gosec
#     - gosimple
#     - govet
#     - ineffassign
#     - misspell
#     - nakedret
#     - nolintlint
#     - revive
#     - staticcheck
#     - stylecheck
#     - typecheck
#     - unconvert
#     - unparam
#     - unused
#     - whitespace

# Linters you should not enable at the moment
# These linters are either deprecated, too aggressive, or cause false positives
#   - gochecknoglobals
#   - gochecknoinits   # too aggressive
#   - godot            # inconsistent use of doc comments is not crucial yet
#   - godox            # overly noisy for TODO comments
#   - goerr113         # enforcing error wrapping isn't needed across the codebase
#   - golint           # deprecated, consider revive or staticcheck instead
#   - gomnd            # too aggressive regarding magic numbers
#   - interfacer       # deprecated and prone to false positives
#   - lll              # line length limit without per-line exceptions isn't feasible
#   - maligned         # unnecessary optimization for your current context
#   - nestif           # complex nested ifs are a low priority right now
#   - prealloc         # could enforce unnecessary allocations and non-idiomatic code
#   - scopelint        # deprecated
#   - testpackage      # specific to test package structure
#   - wsl              # noisy and lacks auto-fixer (https://github.com/bombsimon/wsl/issues/90)
#   - varcheck         # deprecated, replaced by unused
#   - deadcode         # deprecated, replaced by unused
#   - structcheck      # deprecated, replaced by unused
#   - rowserrcheck     # not applicable if sql.Rows isn't in use
